const express = require('express');
const cors = require('cors');
require('dotenv').config();
const app = express();
app.use(cors());
app.use(express.json());
app.get('/health', (req, res) => res.json({status: 'ok', uptime: process.uptime()}));
app.get('/api/data', (req, res) => res.json({items: [], count: 0}));
app.post('/api/data', (req, res) => res.status(201).json({id: 1, ...req.body}));
app.use((err, req, res, next) => res.status(500).json({error: err.message}));
const PORT = process.env.PORT || 3000;
if (require.main === module) app.listen(PORT, () => console.log(`Server on ${PORT}`));
module.exports = app;
